### ISSUE TITLE
Remove a label / list of labels

### ISSUE THREAD

**Issue by ChristianKuehnel** [ChristianKuehnel/todoistautomation#4]
It would be nice to have the option to remove a particular label from a task. the config could look like this:

```yaml
rules:
  - query: "project:Alexa*To-do-Liste"
    move_to: "Inbox"
    remove_label: "Alexa"
```
